variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "aws_account_id" {
  description = "AWS account ID, used in globally unique resource names"
  type        = string
  default     = "241533126054"
}

variable "service_name" {
  description = "Name prefix for all resources"
  type        = string
  default     = "snake-game"
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t3.micro"
}

variable "ec2_public_key" {
  description = "Public key material for the EC2 key pair (generated by UDAP vault)"
  type        = string
  sensitive   = true
}
